export default function Disclaimer() {
  return (
    <div className="text-center py-6 mt-8 text-text-muted text-xs border-t border-border">
      <p>
        <strong>⚠️ Disclaimer:</strong> This report is generated by AI and is for informational purposes only.
        It does not constitute financial advice, investment recommendations, or solicitation to buy or sell securities.
        Always conduct your own research and consult a qualified financial advisor before making investment decisions.
        Past performance does not guarantee future results. Trading involves risk of loss.
      </p>
    </div>
  );
}
